default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: test
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: blog_app_production
  username: root
  password: <%= ENV['test'] %>
